const languageCodes = {
    English: "en-US",
    Korean: "ko-KR",
    Spanish: "es-ES",
    Chinese: "zh-CN",
    Hindi: "hi-IN",
    Bengali: "bn-BD",
    Portuguese: "pt-PT",
    Russian: "ru-RU",
    Japanese: "ja-JP",
    Marathi: "mr-IN",
    Telugu: "te-IN",
    Turkish: "tr-TR",
    French: "fr-FR",
    German: "de-DE",
    Vietnamese: "vi-VN",
    Tamil: "ta-IN",
    "Yue Chinese": "zh-HK",
    Urdu: "ur-PK",
    Javanese: "jv-ID",
    Italian: "it-IT",
    "Egyptian Arabic": "ar-EG",
    Gujarati: "gu-IN",
    "Iranian Persian": "fa-IR",
    Bhojpuri: "bho-IN",
    "Min Nan Chinese": "zh-TW",
    "Hakka Chinese": "hak-CN",
    "Jin Chinese": "cjy-CN",
    Hausa: "ha-NG",
    Kannada: "kn-IN",
    Indonesian: "id-ID",
    Polish: "pl-PL",
    Yoruba: "yo-NG",
    "Xiang Chinese": "hsn-CN",
    Malayalam: "ml-IN",
    Odia: "or-IN",
    Maithili: "mai-IN",
    Burmese: "my-MM",
    Punjabi: "pa-IN",
    Sunda: "su-ID",
    "Sudanese Arabic": "ar-SD",
    "Algerian Arabic": "ar-DZ",
    "Moroccan Arabic": "ar-MA",
    Ukrainian: "uk-UA",
    Igbo: "ig-NG",
    "Northern Uzbek": "uz-UZ",
    Sindhi: "sd-PK",
    "North Levantine Arabic": "apc-SY",
    Romanian: "ro-RO",
  };
  
  export default languageCodes;